"""
Comprehensive Report Generator for KHUNEHO? Neural Analysis System
Creates detailed markdown reports with dynamic categories, resource tracking, and links
"""
import os
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any
import markdown
import requests

class ReportGenerator:
    """Generates comprehensive markdown reports with sections and resource tracking"""
    
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.report_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
    def generate_comprehensive_report(self, event: str, dynamic_categories: Dict, 
                                    agent_reports: List[Dict], web_context: Dict, 
                                    resource_data: Dict, research_analysis: Dict) -> str:
        """Generate comprehensive markdown report"""
        
        # Create main report file
        report_filename = f"KHUNEHO_Analysis_{self.report_timestamp}.md"
        report_path = self.output_dir / report_filename
        
        # Generate report content
        report_content = self._build_report_content(
            event, dynamic_categories, agent_reports, web_context, resource_data, research_analysis
        )
        
        # Write main report
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        # Generate category-specific detailed reports
        category_files = self._generate_category_reports(
            event, dynamic_categories, agent_reports, web_context, resource_data
        )
        
        # Generate resource usage report
        resource_file = self._generate_resource_report(resource_data)
        
        # Generate summary index
        index_file = self._generate_index_report(report_filename, category_files, resource_file, event)
        
        return str(report_path)
    
    def _build_report_content(self, event: str, dynamic_categories: Dict, 
                             agent_reports: List[Dict], web_context: Dict, 
                             resource_data: Dict, research_analysis: Dict) -> str:
        """Build the main report content"""
        
        content = f"""# KHUNEHO? Neural Analysis System - Comprehensive Report

## Event Analysis: {event}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Analysis ID:** {self.report_timestamp}

---

## Executive Summary

{self._generate_executive_summary(dynamic_categories, agent_reports, research_analysis)}

---

## Dynamic Categories Analysis

{self._generate_categories_overview(dynamic_categories)}

---

## Neural Agent Insights

{self._generate_agent_insights_section(agent_reports)}

---

## Web Context Analysis

{self._generate_web_context_section(web_context)}

---

## Professional Research Analysis

{self._generate_research_section(research_analysis)}

---

## Resource Usage Summary

{self._generate_resource_summary(resource_data)}

---

## Detailed Category Reports

{self._generate_category_links(dynamic_categories)}

---

## Conclusions and Recommendations

{self._generate_conclusions(dynamic_categories, research_analysis)}

---

*Report generated by KHUNEHO? Neural Analysis System*
"""
        return content
    
    def _generate_executive_summary(self, dynamic_categories: Dict, agent_reports: List[Dict], research_analysis: Dict) -> str:
        """Generate executive summary"""
        total_categories = len(dynamic_categories)
        high_relevance_categories = len([cat for cat in dynamic_categories.values() if cat.get('relevance_score', 0) > 0.7])
        
        avg_confidence = 0
        if agent_reports:
            confidences = [getattr(report, 'confidence', 0) for report in agent_reports if hasattr(report, 'confidence')]
            avg_confidence = sum(confidences) / len(confidences) if confidences else 0
        
        summary = f"""
This comprehensive analysis of the event identified **{total_categories} dynamic categories** with **{high_relevance_categories} high-relevance categories**. 

**Key Findings:**
- Neural network confidence averaged {avg_confidence:.2%}
- Most relevant categories: {self._get_top_categories(dynamic_categories, 3)}
- Analysis completed with {len(agent_reports)} specialized neural agents
- Professional research synthesis provided strategic insights

**Critical Insights:**
{self._extract_key_insights(dynamic_categories, research_analysis)}
"""
        return summary
    
    def _generate_categories_overview(self, dynamic_categories: Dict) -> str:
        """Generate overview of all dynamic categories"""
        overview = ""
        
        for category_name, category_data in dynamic_categories.items():
            relevance = category_data.get('relevance_score', 0)
            description = category_data.get('description', '')
            reasoning = category_data.get('ai_reasoning', '')
            
            overview += f"""
### {category_name.replace('_', ' ').title()}
**Relevance Score:** {relevance:.2%}  
**Description:** {description}  
**AI Reasoning:** {reasoning}

**Practical Predictions & Impacts:**
{self._format_predictions(category_data.get('dynamic_parameters', []))}

**Key Indicators:**
{self._format_indicators(category_data.get('key_indicators', []))}

**Time Horizons:**
{self._format_time_horizons(category_data.get('time_horizons', {}))}

---

"""
        return overview
    
    def _generate_agent_insights_section(self, agent_reports: List[Dict]) -> str:
        """Generate section for neural agent insights"""
        insights = ""
        
        for report in agent_reports:
            if hasattr(report, 'neuron_id'):
                neuron_id = report.neuron_id
                prediction = report.class_labels[report.predicted_class] if report.class_labels and hasattr(report, 'predicted_class') else 'unknown'
                confidence = getattr(report, 'confidence', 0)
                reasoning = getattr(report, 'reasoning', 'No reasoning available')
                web_sources = getattr(report, 'web_sources', 0)
                dynamic_prompt = getattr(report, 'dynamic_prompt', 'Standard prompt')
                
                insights += f"""
#### {neuron_id.upper()} Agent Analysis
- **Prediction:** {prediction}
- **Confidence:** {confidence:.2%}
- **Web Sources Analyzed:** {web_sources}
- **Dynamic Prompt Used:** {dynamic_prompt}
- **Reasoning:** {reasoning}

"""
        
        return insights
    
    def _generate_web_context_section(self, web_context: Dict) -> str:
        """Generate web context analysis section"""
        context = ""
        
        for category, articles in web_context.items():
            if articles:
                context += f"""
#### {category.upper()} Context Analysis
"""
                for i, article in enumerate(articles[:3], 1):  # Top 3 articles
                    title = article.get('title', 'No title')
                    snippet = article.get('snippet', 'No snippet')
                    url = article.get('url', '')
                    domain = article.get('domain', 'Unknown')
                    date = article.get('date', 'Unknown date')
                    
                    context += f"""
**Article {i}:** [{title}]({url})
- **Source:** {domain}
- **Date:** {date}
- **Summary:** {snippet}

"""
        
        return context
    
    def _generate_research_section(self, research_analysis: Dict) -> str:
        """Generate professional research analysis section"""
        if not research_analysis:
            return "No research analysis available."
        
        research = ""
        
        # Executive Summary
        exec_summary = research_analysis.get('executive_summary', '')
        if exec_summary:
            research += f"### Professional Executive Summary\n{exec_summary}\n\n"
        
        # Sector Impacts
        sector_impacts = research_analysis.get('sector_impacts', {})
        if sector_impacts:
            research += "### Sector Impact Analysis\n"
            for sector, impact in sector_impacts.items():
                if isinstance(impact, dict):
                    research += f"**{sector.title()}:** {impact.get('impact_level', 'Unknown')} Impact\n"
                    research += f"- Market Sentiment: {impact.get('market_sentiment', 'Unknown')}\n"
                    research += f"- Short-term Effects: {', '.join(impact.get('short_term_effects', []))}\n"
                    research += f"- Long-term Effects: {', '.join(impact.get('long_term_effects', []))}\n\n"
        
        # Future Predictions
        predictions = research_analysis.get('future_predictions', {})
        if predictions:
            research += "### Future Predictions\n"
            for timeframe, prediction in predictions.items():
                research += f"**{timeframe.replace('_', ' ').title()}:** {prediction}\n\n"
        
        # Risk Assessment
        risk = research_analysis.get('risk_assessment', {})
        if risk and isinstance(risk, dict):
            research += "### Risk Assessment\n"
            research += f"**Overall Risk Level:** {risk.get('overall_risk_level', 'Unknown')}\n"
            research += f"**Key Risks:** {', '.join(risk.get('key_risks', []))}\n"
            research += f"**Mitigation Strategies:** {', '.join(risk.get('mitigation_strategies', []))}\n\n"
        
        # Investment Outlook
        investment = research_analysis.get('investment_outlook', {})
        if investment and isinstance(investment, dict):
            research += "### Investment Outlook\n"
            research += f"**Market Outlook:** {investment.get('market_outlook', 'Unknown')}\n"
            research += f"**Risk Level:** {investment.get('risk_level', 'Unknown')}\n"
            recommendations = investment.get('recommendations', [])
            if recommendations:
                research += "**Recommendations:**\n"
                for rec in recommendations:
                    research += f"- {rec}\n"
            research += "\n"
        
        return research
    
    def _generate_resource_summary(self, resource_data: Dict) -> str:
        """Generate resource usage summary"""
        if not resource_data:
            return "No resource data available."
        
        metadata = resource_data.get('analysis_metadata', {})
        total_time = metadata.get('total_analysis_time', 0)
        category_timings = metadata.get('category_timings', {})
        resource_usage = metadata.get('resource_usage', {})
        internet_usage = metadata.get('internet_usage', {})
        device_info = metadata.get('device_info', {})
        
        summary = f"""
### Performance Metrics
- **Total Analysis Time:** {total_time:.2f} seconds
- **Device Used:** {device_info.get('device', 'Unknown')}
- **CPU Cores:** {device_info.get('cpu_count', 'Unknown')}
- **Total Memory:** {device_info.get('total_memory_gb', 0):.1f} GB
- **GPU Available:** {device_info.get('gpu_available', False)}

### Category Processing Times
"""
        
        for category, time_taken in category_timings.items():
            summary += f"- **{category.replace('_', ' ').title()}:** {time_taken:.2f} seconds\n"
        
        summary += "\n### Resource Usage by Operation\n"
        
        for operation, usage in resource_usage.items():
            timestamp = usage.get('timestamp', 'Unknown')
            cpu = usage.get('cpu_percent', 0)
            memory = usage.get('memory_percent', 0)
            gpu_memory = usage.get('gpu_memory_gb', 0)
            
            summary += f"""
**{operation.replace('_', ' ').title()}** ({timestamp})
- CPU Usage: {cpu:.1f}%
- Memory Usage: {memory:.1f}%
- GPU Memory: {gpu_memory:.2f} GB
"""
        
        summary += "\n### Internet Usage\n"
        
        for operation, usage in internet_usage.items():
            urls = usage.get('urls_accessed', [])
            data_size = usage.get('estimated_data_size_mb', 0)
            request_count = usage.get('request_count', 0)
            
            summary += f"""
**{operation.replace('_', ' ').title()}**
- Requests Made: {request_count}
- Data Size: {data_size:.2f} MB
- URLs Accessed: {len(urls)}
"""
        
        return summary
    
    def _generate_category_links(self, dynamic_categories: Dict) -> str:
        """Generate links to detailed category reports"""
        links = "The following detailed category reports are available:\n\n"
        
        for category_name in dynamic_categories.keys():
            filename = f"Category_{category_name}_{self.report_timestamp}.md"
            links += f"- [{category_name.replace('_', ' ').title()}](./{filename})\n"
        
        return links
    
    def _generate_conclusions(self, dynamic_categories: Dict, research_analysis: Dict) -> str:
        """Generate conclusions and recommendations"""
        conclusions = """
### Key Conclusions

Based on the comprehensive analysis of dynamic categories and neural agent insights:

"""
        
        # Top categories
        top_categories = self._get_top_categories(dynamic_categories, 3)
        conclusions += f"**Most Impactful Categories:** {', '.join(top_categories)}\n\n"
        
        # Research insights
        if research_analysis:
            exec_summary = research_analysis.get('executive_summary', '')
            if exec_summary:
                conclusions += f"**Professional Assessment:** {exec_summary}\n\n"
        
        conclusions += """
### Strategic Recommendations

1. **Monitor High-Relevance Categories:** Focus continuous monitoring on categories with relevance scores above 70%
2. **Track Key Indicators:** Implement monitoring systems for the identified key indicators
3. **Resource Allocation:** Allocate resources based on category relevance scores and time horizons
4. **Risk Management:** Implement mitigation strategies for identified risks
5. **Opportunity Pursuit:** Leverage identified opportunities in high-impact areas

### Next Steps

- Schedule regular reviews of high-relevance categories
- Implement automated monitoring for key indicators
- Update analysis parameters based on new data
- Expand analysis scope as needed based on emerging patterns

"""
        
        return conclusions
    
    def _generate_category_reports(self, event: str, dynamic_categories: Dict, 
                                 agent_reports: List[Dict], web_context: Dict, 
                                 resource_data: Dict) -> List[str]:
        """Generate detailed reports for each category"""
        category_files = []
        
        for category_name, category_data in dynamic_categories.items():
            filename = f"Category_{category_name}_{self.report_timestamp}.md"
            filepath = self.output_dir / filename
            
            content = f"""# {category_name.replace('_', ' ').title()} - Detailed Analysis

**Event:** {event}  
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Relevance Score:** {category_data.get('relevance_score', 0):.2%}

## Category Overview
{category_data.get('description', 'No description available')}

## AI Reasoning for Category Selection
{category_data.get('ai_reasoning', 'No reasoning available')}

## Practical Predictions Analysis
{self._detailed_predictions_analysis(category_data.get('dynamic_parameters', []), category_name)}

## Key Performance Indicators
{self._detailed_indicators_analysis(category_data.get('key_indicators', []))}

## Time Horizon Analysis
{self._detailed_time_horizons_analysis(category_data.get('time_horizons', {}))}

## Neural Agent Contributions
{self._category_agent_analysis(category_name, agent_reports)}

## Web Context Relevance
{self._category_web_analysis(category_name, web_context)}

## Resource Usage for This Category
{self._category_resource_usage(category_name, resource_data)}

## Specific Recommendations for {category_name.replace('_', ' ').title()}
{self._category_specific_recommendations(category_name, category_data)}

## Links and Resources
{self._category_resource_links(category_name, web_context)}

---

*Category-specific analysis generated by KHUNEHO? Neural Analysis System*
"""
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            
            category_files.append(filename)
        
        return category_files
    
    def _generate_resource_report(self, resource_data: Dict) -> str:
        """Generate detailed resource usage report"""
        filename = f"Resource_Usage_{self.report_timestamp}.md"
        filepath = self.output_dir / filename
        
        metadata = resource_data.get('analysis_metadata', {})
        
        content = f"""# Resource Usage Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Analysis ID:** {self.report_timestamp}

## System Information
- **Device:** {metadata.get('device_info', {}).get('device', 'Unknown')}
- **CPU Cores:** {metadata.get('device_info', {}).get('cpu_count', 'Unknown')}
- **Total Memory:** {metadata.get('device_info', {}).get('total_memory_gb', 0):.1f} GB
- **GPU Available:** {metadata.get('device_info', {}).get('gpu_available', False)}

## Performance Analysis
- **Total Analysis Time:** {metadata.get('total_analysis_time', 0):.2f} seconds

## Detailed Timing Breakdown
"""
        
        category_timings = metadata.get('category_timings', {})
        for operation, time_taken in category_timings.items():
            content += f"- **{operation.replace('_', ' ').title()}:** {time_taken:.2f} seconds\n"
        
        content += "\n## Resource Usage by Operation\n"
        
        resource_usage = metadata.get('resource_usage', {})
        for operation, usage in resource_usage.items():
            content += f"""
### {operation.replace('_', ' ').title()}
- **Timestamp:** {usage.get('timestamp', 'Unknown')}
- **CPU Usage:** {usage.get('cpu_percent', 0):.1f}%
- **Memory Used:** {usage.get('memory_used_gb', 0):.2f} GB ({usage.get('memory_percent', 0):.1f}%)
- **GPU Memory:** {usage.get('gpu_memory_gb', 0):.2f} GB
- **GPU Utilization:** {usage.get('gpu_utilization', 0):.1f}%
"""
        
        content += "\n## Internet Usage Analysis\n"
        
        internet_usage = metadata.get('internet_usage', {})
        for operation, usage in internet_usage.items():
            urls = usage.get('urls_accessed', [])
            content += f"""
### {operation.replace('_', ' ').title()}
- **Requests Made:** {usage.get('request_count', 0)}
- **Estimated Data Size:** {usage.get('estimated_data_size_mb', 0):.2f} MB
- **Timestamp:** {usage.get('timestamp', 'Unknown')}

**URLs Accessed:**
"""
            for url in urls:
                content += f"- {url}\n"
            content += "\n"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return filename
    
    def _generate_index_report(self, main_report: str, category_files: List[str], 
                             resource_file: str, event: str) -> str:
        """Generate index report with all file links"""
        filename = f"Analysis_Index_{self.report_timestamp}.md"
        filepath = self.output_dir / filename
        
        content = f"""# KHUNEHO? Analysis Index

**Event:** {event}  
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Analysis ID:** {self.report_timestamp}

## Report Files

### Main Analysis Report
- [Comprehensive Analysis Report]({main_report})

### Category-Specific Reports
"""
        
        for cat_file in category_files:
            category_name = cat_file.replace(f"Category_", "").replace(f"_{self.report_timestamp}.md", "").replace("_", " ").title()
            content += f"- [{category_name} Detailed Analysis]({cat_file})\n"
        
        content += f"""
### Resource and Performance Reports
- [Detailed Resource Usage]({resource_file})

## Report Summary
This analysis generated **{len(category_files) + 2} reports** covering:
- Main comprehensive analysis
- {len(category_files)} category-specific detailed reports  
- Resource usage and performance tracking

## Quick Access Links
- [Executive Summary]({main_report}#executive-summary)
- [Dynamic Categories Overview]({main_report}#dynamic-categories-analysis)
- [Neural Agent Insights]({main_report}#neural-agent-insights)
- [Resource Usage Summary]({main_report}#resource-usage-summary)

---

*Index generated by KHUNEHO? Neural Analysis System*
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return filename
    
    # Helper methods for formatting content
    def _format_predictions(self, predictions: List[Dict]) -> str:
        if not predictions:
            return "No predictions available."
        
        formatted = ""
        for i, pred in enumerate(predictions, 1):
            prediction = pred.get('prediction', 'Unknown prediction')
            impact = pred.get('impact', 'No impact specified')
            timeline = pred.get('timeline', 'Unknown timeline')
            
            formatted += f"""
**Prediction {i}:** {prediction}
- **Impact:** {impact}
- **Timeline:** {timeline}
"""
        
        return formatted
    
    def _format_parameters(self, parameters: List[Dict]) -> str:
        if not parameters:
            return "No parameters defined."
        
        formatted = ""
        for param in parameters:
            name = param.get('parameter', 'Unknown')
            desc = param.get('description', 'No description')
            formatted += f"- **{name}:** {desc}\n"
        
        return formatted
    
    def _format_indicators(self, indicators: List[str]) -> str:
        if not indicators:
            return "No indicators defined."
        
        return "\n".join([f"- {indicator}" for indicator in indicators])
    
    def _generate_practical_impact_summary(self, prediction: str, impact: str, timeline: str) -> str:
        """Generate practical impact summary for layman understanding"""
        
        # Generate practical advice based on prediction type
        prediction_lower = prediction.lower()
        
        if 'market' in prediction_lower and 'volatility' in prediction_lower:
            return "If you have investments, expect bigger ups and downs. Consider holding steady or moving to safer investments temporarily."
        elif 'trading volume' in prediction_lower:
            return "More people will be buying and selling. If you're trading, be prepared for rapid price changes."
        elif 'government' in prediction_lower and 'slow' in impact.lower():
            return "Government services and decisions may take longer. Plan ahead for permits, approvals, or government services."
        elif 'public opinion' in prediction_lower:
            return "People will have strong opinions. Be prepared for heated discussions on social media and in person."
        elif 'economic growth' in prediction_lower:
            return "The economy may grow slower or faster than expected. This could affect job security and business opportunities."
        elif 'inflation' in prediction_lower:
            return "Prices may change faster than usual. Your grocery bills and expenses could increase noticeably."
        elif 'job market' in prediction_lower:
            return "Employment conditions may shift. If job hunting, expect more or fewer openings depending on the direction."
        elif 'tech sector' in prediction_lower:
            return "Technology companies may see big changes. If you work in tech or invest in it, watch for major shifts."
        elif 'policy' in prediction_lower:
            return "Rules and regulations may change. Stay informed about how this affects your business or daily life."
        else:
            return f"Pay attention to developments in this area over the {timeline}. This could affect your decisions and planning."
    
    def _format_time_horizons(self, horizons: Dict) -> str:
        if not horizons:
            return "No time horizons defined."
        
        formatted = ""
        for horizon, description in horizons.items():
            formatted += f"- **{horizon.replace('_', ' ').title()}:** {description}\n"
        
        return formatted
    
    def _get_top_categories(self, dynamic_categories: Dict, count: int = 3) -> List[str]:
        """Get top categories by relevance score"""
        sorted_categories = sorted(
            dynamic_categories.items(), 
            key=lambda x: x[1].get('relevance_score', 0), 
            reverse=True
        )
        
        return [cat[0].replace('_', ' ').title() for cat in sorted_categories[:count]]
    
    def _extract_key_insights(self, dynamic_categories: Dict, research_analysis: Dict) -> str:
        """Extract key insights from analysis"""
        insights = []
        
        # Top category insights
        top_categories = self._get_top_categories(dynamic_categories, 2)
        insights.append(f"Primary focus areas: {', '.join(top_categories)}")
        
        # Research insights
        if research_analysis:
            risk_level = research_analysis.get('risk_assessment', {}).get('overall_risk_level', 'Unknown')
            insights.append(f"Overall risk assessment: {risk_level}")
        
        return "\n".join([f"- {insight}" for insight in insights])
    
    def _detailed_predictions_analysis(self, predictions: List[Dict], category: str) -> str:
        """Generate detailed practical predictions analysis"""
        if not predictions:
            return "No predictions available for this category."
        
        analysis = f"### Practical Predictions for {category.replace('_', ' ').title()}\n\n"
        
        for i, pred in enumerate(predictions, 1):
            prediction = pred.get('prediction', 'Unknown prediction')
            impact = pred.get('impact', 'No impact specified')
            timeline = pred.get('timeline', 'Unknown timeline')
            
            analysis += f"""
#### Prediction {i}: {prediction}

**What Will Happen:**
{prediction}

**Real-World Impact:**
{impact}

**When to Expect This:**
{timeline}

**What This Means for You:**
{self._generate_practical_impact_summary(prediction, impact, timeline)}

---

"""
        
        return analysis
    
    def _detailed_parameters_analysis(self, parameters: List[Dict], category: str) -> str:
        """Generate detailed parameter analysis"""
        if not parameters:
            return "No parameters available for this category."
        
        analysis = f"### Parameter Analysis for {category.replace('_', ' ').title()}\n\n"
        
        for param in parameters:
            name = param.get('parameter', 'Unknown')
            desc = param.get('description', 'No description')
            analysis += f"**{name}**: {desc}\n\n"
        
        return analysis
    
    def _detailed_indicators_analysis(self, indicators: List[str]) -> str:
        """Generate detailed indicators analysis"""
        if not indicators:
            return "No indicators available."
        
        analysis = "### Key Performance Indicators\n\n"
        for indicator in indicators:
            analysis += f"- **{indicator}**: Monitor this indicator for category performance\n"
        
        return analysis
    
    def _detailed_time_horizons_analysis(self, horizons: Dict) -> str:
        """Generate detailed time horizons analysis"""
        if not horizons:
            return "No time horizons defined."
        
        analysis = "### Time Horizon Analysis\n\n"
        for horizon, description in horizons.items():
            analysis += f"**{horizon.replace('_', ' ').title()}**: {description}\n\n"
        
        return analysis
    
    def _category_agent_analysis(self, category: str, agent_reports: List[Dict]) -> str:
        """Generate category-specific agent analysis"""
        relevant_agents = []
        
        for report in agent_reports:
            if hasattr(report, 'neuron_id'):
                neuron_id = report.neuron_id
                reasoning = getattr(report, 'reasoning', '').lower()
                
                # Check if agent is relevant to this category
                if category.replace('_', ' ') in reasoning or category.split('_')[0] in reasoning:
                    prediction = report.class_labels[report.predicted_class] if report.class_labels and hasattr(report, 'predicted_class') else 'unknown'
                    confidence = getattr(report, 'confidence', 0)
                    relevant_agents.append(f"- **{neuron_id.upper()}**: {prediction} (confidence: {confidence:.2%})")
        
        if relevant_agents:
            return "### Relevant Neural Agents\n\n" + "\n".join(relevant_agents)
        else:
            return "### Relevant Neural Agents\n\nNo specific agent contributions identified for this category."
    
    def _category_web_analysis(self, category: str, web_context: Dict) -> str:
        """Generate category-specific web context analysis"""
        relevant_sources = []
        
        for context_category, articles in web_context.items():
            if articles:
                for article in articles[:2]:  # Top 2 articles
                    title = article.get('title', '').lower()
                    if category.replace('_', ' ') in title or category.split('_')[0] in title:
                        url = article.get('url', '')
                        relevant_sources.append(f"- [{article.get('title', 'No title')}]({url})")
        
        if relevant_sources:
            return "### Relevant Web Sources\n\n" + "\n".join(relevant_sources)
        else:
            return "### Relevant Web Sources\n\nNo specific web sources identified for this category."
    
    def _category_resource_usage(self, category: str, resource_data: Dict) -> str:
        """Generate category-specific resource usage"""
        metadata = resource_data.get('analysis_metadata', {})
        category_timings = metadata.get('category_timings', {})
        
        timing = category_timings.get(category, 0)
        
        return f"""### Resource Usage for This Category
- **Processing Time:** {timing:.2f} seconds
- **Memory Usage:** See detailed resource report
- **Network Requests:** See detailed resource report
"""
    
    def _category_specific_recommendations(self, category: str, category_data: Dict) -> str:
        """Generate category-specific recommendations"""
        relevance = category_data.get('relevance_score', 0)
        
        recommendations = f"""### Specific Recommendations for {category.replace('_', ' ').title()}

**Priority Level:** {'High' if relevance > 0.7 else 'Medium' if relevance > 0.4 else 'Low'}

**Action Items:**
1. Monitor key indicators identified for this category
2. Track parameters over specified time horizons
3. Implement early warning systems for critical thresholds
4. Regular review of category relevance based on new data

**Monitoring Frequency:** 
- {'Daily' if relevance > 0.8 else 'Weekly' if relevance > 0.6 else 'Monthly'}
"""
        
        return recommendations
    
    def _category_resource_links(self, category: str, web_context: Dict) -> str:
        """Generate category-specific resource links"""
        links = "### External Resources and Links\n\n"
        
        # Add relevant web sources
        for context_category, articles in web_context.items():
            if articles:
                links += f"#### {context_category.upper()} Sources\n"
                for article in articles[:3]:
                    title = article.get('title', 'No title')
                    url = article.get('url', '')
                    domain = article.get('domain', 'Unknown')
                    links += f"- [{title}]({url}) (Source: {domain})\n"
                links += "\n"
        
        # Add general monitoring resources
        links += """#### Monitoring Resources
- [Google News](https://news.google.com) - Real-time news monitoring
- [Reuters](https://reuters.com) - Financial and political news
- [Bloomberg](https://bloomberg.com) - Market data and analysis
"""
        
        return links
